[package]
name = "disk-archive"
version = "0.1.0"
authors = ["Garrett Powell <garrett@gpowell.net>"]
edition = "2018"

[dependencies]
multihash = "0.8.0"
diesel = "1.4.3"
blake2-rfc = "0.2.18"
xattr = "0.2.2"
flate2 = "1.0.13"
fuse = "0.3.1"
zip = "0.5.3"
clap = "2.33.0"
