[package]
name = "disk-archive"
version = "0.1.0"
authors = ["Garrett Powell <garrett@gpowell.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
