[package]
name = "disk-archive"
version = "0.1.0"
authors = ["Garrett Powell <garrett@gpowell.net>"]
edition = "2018"

[dependencies]
# File system
xattr = "0.2.2"
filetime = "0.2.8"
fuse = "0.3.1"
relative-path = "1.0.0"
walkdir = "2.2.9"
tempfile = "3.1.0"
fs2 = "0.4.3"

# I/O
iter-read = "0.2.1"
cdchunking = "1.0.0"

# Hashing
blake2 = "0.8.1"

# Compression
flate2 = "1.0.13"
xz2 = "0.1.6"
lz4 = "1.23.1"

# Encryption
sodiumoxide = "0.2.5"
zeroize = { version = "1.1.0", features = ["zeroize_derive"] }
rand = { version = "0.7.2", features = ["small_rng"] }

# Error handling
thiserror = "1.0.4"

# Serialization
serde = { version = "1.0.103", features = ["derive"] }
rmp = "0.8.8"
rmp-serde = "0.14.0"

# Misc
num-integer = "0.1.41"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
