name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install native dependencies
        run: sudo apt-get install libacl1-dev libfuse-dev pkg-config

      - name: Build
        run: cargo build --all-features

      - name: Run tests
        run: cargo test --verbose --features 'file-metadata hash-algorithms encryption compression repo-version repo-value repo-file repo-content'
