name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Start Redis
        uses: zhulik/redis-action@1.1.0
      - name: Build
        run: cargo build
      - name: Run tests
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_BUCKET: lostatc-acid-store
          REDIS_URL: redis://localhost:6379
        run: cargo test --verbose --all-features
